### PR TITLE
i18n: Add Czech translation of nutrition values

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
Hi @lneugebauer! I look at the list of the nutrition values and it seems a little weird. I don't think cholesterol is stated in food nutrition values. One more think — what is trans fat? It looks like the synonym of saturated fat. Could you look at it, please?

Btw, could you take a screenshot of these newly added items? I'd like to check ordering of the nutrition values, but I don't want to waste time with setup of the app project locally.

**Comment by ceskyDJ** [comment]
I looked to the web version and it's just the same there. So, let it be. I tried to translate it, so it could be ok.

**Comment by lneugebauer** [comment]
Hi @ceskyDJ, here is an Android screenshot:
android

And here is one from the web client:
web

Maybe you can find more information in the [web client resources](https://app.transifex.com/nextcloud/nextcloud/cookbook/).
I may change the ordering in the app before releasing it to match the web version.

**Comment by lneugebauer** [comment]
Be aware there is currently a bug (nextcloud/cookbook#2024) in the 10.x version where you can not edit nutrition information via the web client.

**Comment by ceskyDJ** [comment]
Thanks for noticing. I don't need this functionality, I just wanted to check how nutritional values are organized.

**Pull request merged**
