### PR TITLE
Login Screen - URL checking

### PR DESCRIPTION
**Pull request by AndusDEV**
Most of Android keyboards replace "https" with "HTTPS" if you have autocorrect enabled. It happened to me and I had to replace it to lowercase for it to work. This commit just adds ".toLowerCase()" to the checks In LoginViewModel.kt.

### CODE REVIEW

**Comment by lneugebauer** [comment]
Hi @AndusDEV, thank you for your contribution - much appreciated. I agree that the isValidUrl check should be successful whether its https or HTTPS.
However, please undo the other changes, as the user may have a case sensitive server setup and I don't wanna mess with that.

**Comment by AndusDEV** [comment]
@lneugebauer I've just reverted the second commit. It should be good to go now

**Comment by lneugebauer** [comment]
@AndusDEV please fix the ktlint issues. After that I'll merge the pr.

**Comment by AndusDEV** [comment]
@lneugebauer I've just realised I used a completely wrong function. I fixed it now, the build is successing, and running just fine

**Pull request merged**
