### PR TITLE
l10n: Add Czech translation for auth error

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
Hmm, is it l10n or i18n :D? I looked to the history and saw that my last pull request contains i18n. I read some information articles about this problem but I'm completely lost in the naming of these things :D.

**Comment by lneugebauer** [comment]
Thank you for regularly updating the Czech translation!

I think it's i18n. As far as I understand it, i18n means that your software is available in different languages, and l10n means that it also respects different date formats, rtl and ltr reading directions, and so on.

**Comment by ceskyDJ** [comment]
> Thank you for regularly updating the Czech translation!

No problem. I just try to keep my promises :D.

> I think it's i18n. As far as I understand it, i18n means that your software is available in different languages, and l10n means that it also respects different date formats, rtl and ltr reading directions, and so on.

Oh, nice. It makes sense. As you already merge it, I understand it like you are ok with current state, so I won't have to rename it :D. Thanks for explanation! I don't know, why other people can't say it just that clear :D.

**Comment by ceskyDJ** [comment]
Btw, the Github

**Pull request merged**
